### ISSUE TITLE
Reports from misconfigured date for countdown.

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hoprnet-org#102]
# Introduction

Multiple users have shared with us that the countdown looks different to them.

# Task description

- [ ] Ensure the timezone is included in our countdown.

# Definition of complete

The task is completed when the countdown is uniform across our users.

# Testing criteria

- [ ] Compare with a few users to ensure they see the same countdown.

**Comment by kitschbent** [comment]
These were all screencapped within 5 mins of one another and shared. Therefore, they should be off only by ~5 minutes you would think, maybe 6 given some lag in doing the task...

Me, Brave 64bit on Big Sur.  I'm a full day off from the others. Clock is right, confirmed on mobile, checked system clock.
![photo_2021-02-14 08 45 34](https://user-images.githubusercontent.com/34662130/107878509-30a76980-6ea1-11eb-891c-17a6dd50502f.jpeg)

From Ambassador channel:

![photo_2021-02-14 08 44 33](https://user-images.githubusercontent.com/34662130/107878543-651b2580-6ea1-11eb-8641-9243bdde821f.jpeg)

![photo_2021-02-14 08 45 24](https://user-images.githubusercontent.com/34662130/107878551-6d736080-6ea1-11eb-9378-f5900e446c49.jpeg)
