### ISSUE TITLE
[ website bug ] Links on /node are broken, info doubled

### ISSUE THREAD

**Issue by kitschbent** [hoprnet/hoprnet-org#103]
# Page

hoprnet.org/node

# Current behavior

<img width="1022" alt="Screen Shot 2021-02-14 at 8 38 16 AM" src="https://user-images.githubusercontent.com/34662130/107878353-fdb0a600-6e9f-11eb-896d-cc609cacf4ab.png">

# Expected behavior

The links are all wrong. Github doesn't come here, the one for docs goes to the old RTD 404, and the whole div on the right is a copy/paste from the one on the left, that info is missing.

Important because we have people in the chat wanting to buy nodes pre-launch

# Possible solution

fix links, add correct info into div on the right

# Usepastel link

(Write your answer here.)

# Screenshots

## Detailed Description

(Write your answer here.)

## Context (Environment)

- Device: macbook
- OS: big sur
- Browser: brave 64bit
- Version:
- Resolution:

**Comment by jjperezaguinaga** [comment]
Solved in #105
