### ISSUE TITLE
Wrong link on https://hoprnet.org/node

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#107]
# Page
On https://hoprnet.org/node

# Current behavior
-wrong wording

# Expected behavior
Link properly

# Possible solution
Please re-set the running text in the left column:
"If you want to run a node on your own hardware without the HOPR Node PC, that's perfectly acceptable and possible as well! Check out our Github (https://github.com/hoprnet) for more in-depth details on how to install.
START NOW (https://docs.hoprnet.org/en/latest/src/install-hoprd/index.html)"

# Screenshots
Currently: wrong wording, linking
![Bildschirmfoto 2021-02-15 um 11 20 26](https://user-images.githubusercontent.com/78225531/107935319-86534300-6f81-11eb-9eeb-265dbdf64caf.png)

## Context (Environment)
- Device: 
- OS: 
- Browser:
- Version:
- Resolution:

**Comment by jjperezaguinaga** [comment]
Already solved, closing.
