### ISSUE TITLE
State "2 of 3" and "3 of 3": remove "Mainnet" out of the Roadmap

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#113]
On "…/token": Instead of "Jungfrau Release (Mainnet)", write "Jungfrau Release".

EN: "Jungfrau Release (Mainnet)" - "Jungfrau Release"
GER: "Jungfrau Release (Mainnet)" - "Jungfrau Release"
ESP: "Lanzamiento Jungfrau (Mainnet)" - "Lanzamiento Jungfrau"
CN: "发布主网 JUNGFRAU" – "JUNGFRAU"
JP: "Jungfrauリリース（メインネット)" – "Jungfrauリリース"
KOR: "융프라우(Jungfrau) 공개 (메인넷)" – "융프라우(Jungfrau) 공개"
POR: "Jungfrau é Lançado (Rede principal)" – "Jungfrau é Lançado"
RU: "Релиз Jungfrau (Основная сеть)" – "Релиз Jungfrau"
TR: "Jungfrau Sürümü (Mainnet)" – "Jungfrau Sürümü"

**Comment by jjperezaguinaga** [comment]
Completed in #114
