### ISSUE TITLE
State 3 of 3 of /token AND /win: insert Balancer-API

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#125]
# Page 
https://hoprnet-org-v2-git-development.hoprnet.vercel.app/token 
AND 
/win (from the 24th onwards) 

# Current behavior 
Replace the Fixpreis with the Balancer-API. 
@jjperezaguinaga please provide and insert the link when available # Expected behavior
![Bildschirmfoto 2021-02-19 um 13 39 11](https://user-images.githubusercontent.com/78225531/108506654-6f7e5a80-72b9-11eb-9daf-a058cc0b83ae.png)

**Comment by ruddygasol94** [comment]
@jjperezaguinaga 
Currently, we have a fetch from mainnet, is that the correct API?

**Comment by jjperezaguinaga** [comment]
@ruddygasol94 that's correct, although let me double-check with @SCBuergel on this.
