### ISSUE TITLE
/token: remove the "}"

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#137]
# Page
https://hoprnet-org-v2.hoprnet.vercel.app/token?stage=pre-sale

# Current behavior
![Bildschirmfoto 2021-02-20 um 09 23 40](https://user-images.githubusercontent.com/78225531/108589148-5af39e00-735d-11eb-8834-f99ac0d9ebf3.png)

# Expected behavior
remove it

## Context (Environment)
- Device: iPhone 6s
- OS: 14.4
- Browser: Safari

**Comment by jjperezaguinaga** [comment]
Solved in #136
