### ISSUE TITLE
State "2 of 3" and "3 of 3": broken disclaimer, Hero/Mobile/when clicking on "Community Pre-Launch"

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#17]
![IMG_2069 PNG](https://user-images.githubusercontent.com/78225531/106505113-23b17000-64c8-11eb-9977-d7be63038d2b.png)

TARGET:
<img width="312" alt="Figma_Disclaimer_Mobile" src="https://user-images.githubusercontent.com/78225531/106505122-2613ca00-64c8-11eb-9b5e-afa5ccad8ea5.png">

**Comment by jjperezaguinaga** [comment]
Taking care of this now
