### ISSUE TITLE
/about-us: remove Menglu, add Amira

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#171]
# Page
https://hoprnet.org/de/about-us

# Current behavior
dated

# Expected behavior
- Menglu 
- add Amira: 
Amira Bouguera 
Cryptographer and protocol engineer 

Link of icon: https://drive.google.com/file/d/14x6WzL8OBoswdDJli1K52j5i89s5zgP2/view?usp=sharing

**Comment by ruddygasol94** [comment]
Can we have access to the icon, please?

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 Sorry, now enabled. Great that you work on it!
