### ISSUE TITLE
/win make the destinations accessible

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#180]
# Page
/win

# Current behavior
Only the latest "San Francisco" is accessible

# Expected behavior
- "Tokyo" initially opened
- all destinations are accessible

**Comment by ruddygasol94** [comment]
Can we have the URL of each video, please?

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 Theyr‘e already "inside" the closed accordeon. Since the competition ended, only San Francisco remained open, it‘s rather an control-setting. Let me know if you need further feedback, the links of the destination-links.

**Comment by ruddygasol94** [comment]
@ReinhardSchmidt  Ohh, the thing is that the URL was fetched from an API. So the URLs aren't in the accordeons. @jjperezaguinaga I also check de API code and I couldn't find it. Thanks in advance.

**Comment by ReinhardSchmidt** [comment]
01-Tokyo: https://vimeo.com/515841426
02-Seoul: https://vimeo.com/515842327
03-Shanghai: https://vimeo.com/515843265
04-Hanoi: https://vimeo.com/515843905
05-Moscow: https://vimeo.com/515844733
06-Istanbul: https://vimeo.com/515845437
07-Zurich: https://vimeo.com/515846141
08-Madrid: https://vimeo.com/515846998
09-Sao Paolo: https://vimeo.com/515847802
10-San Francisco: https://vimeo.com/515848789

**Comment by ReinhardSchmidt** [comment]
Before we close this: could you als load the list with TOKYO already open?
