### ISSUE TITLE
/token cut balancer chart on the right, rename the headline

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#183]
# Page
/token

# Current behavior
old state

# Expected behavior
- Change “Balancer Launch” to “Now on Uniswap”
- cut the balancer-chart on the right side
- ![Bildschirmfoto 2021-03-09 um 11 30 17](https://user-images.githubusercontent.com/78225531/110457422-e80f5480-80ca-11eb-903a-6c11a2d0cc5c.png)

**Comment by ruddygasol94** [comment]
At the moment, the "Now on Uniswap" text is fixed in the code. It's required to put in the translations?
