### ISSUE TITLE
Remove Menglu and William, replace Peter's photo with his hopr icon

### ISSUE THREAD

**Issue by WRRichter** [hoprnet/hoprnet-org#189]
# Introduction

In the /about-us section there is an update required to reflect Menglu and William leaving the team as well as the implementation of an icon instead of Peter's photo

# Task description

Remove the Menglu and William asset from the page, modify the Peter asset

# Definition of complete

Menglu and William no longer on the website, Peter appearing as a hopr-ized icon

# Testing criteria

If Menglu and William no longer appear in the People Building the HOPR Network section of /about-us

# Additional notes

![image](https://user-images.githubusercontent.com/77666766/110808258-197f5000-8284-11eb-8473-f34568fa1801.png)

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 I first have to draw an icon for Peter, noted for next week. Please do the other mentioned removal-tasks and do in the same go https://github.com/hoprnet/hoprnet-org/issues/171
