### ISSUE TITLE
/token: remove white frame in the background

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#192]
# Page
/token

# Current behavior
Background-element still in two columns
![Bildschirmfoto 2021-03-12 um 16 35 24](https://user-images.githubusercontent.com/78225531/110962181-f79fcf00-8350-11eb-9237-18598de7f6ed.png)

# Expected behavior
as on /win
![Bildschirmfoto 2021-03-12 um 16 29 46](https://user-images.githubusercontent.com/78225531/110962263-100fe980-8351-11eb-83d7-7676b259094e.png)

**Comment by jjperezaguinaga** [comment]
Solved already.
