### ISSUE TITLE
/home Missing logos in partners

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#194]
# Page
/home

# Current behavior
for some reason all logos went missing

# Expected behavior
please bring back the logos
![Bildschirmfoto 2021-03-16 um 10 47 51](https://user-images.githubusercontent.com/78225531/111296866-439e8c80-864d-11eb-9b11-713fd4c78172.png)

**Comment by ruddygasol94** [comment]
It looks like was a network issue or maybe an error on deploying. I actually I can see the logos.

**Comment by jjperezaguinaga** [comment]
Indeed, the logos are there, closing this one for now.
