### ISSUE TITLE
/token New Display issues

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#195]
# Page
basing this judgement on the state of the website on „https://hoprnet-org-v2-git-obsidiandev-after-launch-hoprnet.vercel.app/de/“
/win
/token

# Current behavior
transparent elements, empty spaces and even colour shifts.
Also, the red-fall-back-colours are displayed on the first Vimeo-block on /win
The hopr Logo went missing in the menue bar (I couldn‘t see it, Jose could).

# Expected behavior
all necessary stuff is visible

# Browser
Chrome, Desktop, Version 89.0.4389.82 (Offizieller Build) (arm64)

![Bildschirmfoto 2021-03-16 um 12 16 00](https://user-images.githubusercontent.com/78225531/111305972-ec51e980-8657-11eb-8f53-2a68f3f9fbe1.png)
![Bildschirmfoto 2021-03-16 um 13 09 52](https://user-images.githubusercontent.com/78225531/111306814-fb856700-8658-11eb-904d-a675595ee7ae.png)
![Bildschirmfoto 2021-03-16 um 13 00 57](https://user-images.githubusercontent.com/78225531/111305997-f247ca80-8657-11eb-8a8d-22c75cf561fc.png)
![Bildschirmfoto 2021-03-16 um 13 01 15](https://user-images.githubusercontent.com/78225531/111306013-f673e800-8657-11eb-899d-a3c78b33f602.png)

**Comment by ruddygasol94** [comment]
The assets could take a long to load. Actually, Vimeo videos are the slowest in the page load. I can see all the assets, only in the first load took a while, in the next re-loads it took less time.

**Comment by ReinhardSchmidt** [comment]
You‘re right, from home it looks normal. Many thanks
