### ISSUE TITLE
[ website bug ] Website displays wrong year # for token release sched

### ISSUE THREAD

**Issue by kitschbent** [hoprnet/hoprnet-org#196]
# Page

hoprnet.org/token

# Current behavior

the website currently says full release in 5 years. The chart, our internal info, etc says 4. 

# Expected behavior

Should say "4 years" in the ENGLISH.

# Possible solution

change 5 to 4

<img width="1134" alt="Screen Shot 2021-03-17 at 10 03 24 AM" src="https://user-images.githubusercontent.com/34662130/111480574-883b2e00-8708-11eb-993d-f1d8e065b70d.png">

**Comment by ruddygasol94** [comment]
Done, I have changed the year numbers in translation files. I'm not sure about Chinese, maybe if someone could check it, it would be awesome. Thanks.

**Comment by kitschbent** [comment]
**Chinese** - waiting on translator

**Japanese**  

1億3000万の初期循環供給から始まり、HOPRトークンは4年間でリリースされます。 すべてのHOPRトークンの4分の1は、データを中継するための報酬としてユーザーのみに配布されます。

**Korean** - waiting on translator

**Comment by kitschbent** [comment]
**Chinese**

从初始供应1.3亿开始,HOPR代币将在四年内释放完。总量的四分之一将保留给对帮助中继覆盖流量的权益质押者的奖励。

**Comment by kitschbent** [comment]
**Korean** - waiting on translator

**Comment by kitschbent** [comment]
@ReinhardSchmidt I think I have all of them ready now!

**Comment by kitschbent** [comment]
@ruddygasol94  ^^ thanks! I think this takes care of all of them, I saw your other changes

appreciated!
