### ISSUE TITLE
text detail: /node 

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#200]
# Page
/node

# Current behavior
dated txt

# Expected behavior
Cut in the section "Your HOPR Hardware Node":
"However, we are only making an initial 100 node PCs available, so we highly recommend ordering now."

**Comment by ruddygasol94** [comment]
![Captura de Pantalla 2021-03-22 a la(s) 12 08 29](https://user-images.githubusercontent.com/11565775/112037875-d2a51c00-8b07-11eb-91bd-f6e37a91c109.png)

Do I have to replace the text "If you want..." with the text above? or add it?

Thanks.

**Comment by ReinhardSchmidt** [comment]
Your screenshot has the headline from the right side on the left. Please compare it to my screenshot of /node: just cut the marked section in the right column.

![Bildschirmfoto 2021-03-23 um 17 09 04](https://user-images.githubusercontent.com/78225531/112121726-d7c5a200-8bbf-11eb-9df7-bdc715035349.png)

**Comment by jjperezaguinaga** [comment]
@ruddygasol94 this one is still open
