### ISSUE TITLE
/token Chart 2

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#204]
# Page
/token
# Current behavior
When looking at the chart:

people assume that the timespan is only 48 months, but in reality it‘s 52.

# Expected behavior
Therefore, we switched the wording of the x-Axis – see the current pull-request 203.

But is it maybe possible to only display the following exact points on the x-Axis? 
Rule: first and last + every third, beginning with pos. "Month 3" (the third in the JSON) 

Source-layout of this screenshot is the pdf-version.
<img width="882" alt="Bildschirmfoto 2021-03-23 um 23 21 34" src="https://user-images.githubusercontent.com/78225531/112171103-dca44900-8bf3-11eb-9dc2-945ffa578455.png">

**Comment by ruddygasol94** [comment]
![Captura de Pantalla 2021-03-30 a la(s) 16 37 53](https://user-images.githubusercontent.com/11565775/113065544-50a39b80-9176-11eb-8e18-e4968f944fe1.png)

Here is a preview. Let me know if that its ok

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 Left side looks correct. Can you also display "Month 52" as an exception? As the community didn´t understand it before.

And I guess this exact choice of  markers x-Axis is NOT possible, then we‘re already happy with displaying "Month 52":
![Bildschirmfoto 2021-03-31 um 10 26 51](https://user-images.githubusercontent.com/78225531/113114450-a6765300-920b-11eb-8b2a-ae73f4b181b4.png)

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 Please wrap this up, it continues to raise questions from the Community. Much appreciated!

**Comment by ruddygasol94** [comment]
![image](https://user-images.githubusercontent.com/11565775/113205108-25c74f00-922b-11eb-8ac9-a7df0fd39308.png)

Actually, I could fix it in that way, I'm gonna commit the change.

**Comment by ruddygasol94** [comment]
Sure, I'm gonna start with the settings for translations labels

**Comment by ruddygasol94** [comment]
Done, Could you check the translations, please?

**Comment by ReinhardSchmidt** [comment]
Many thanks. I meant to update to the new english x-axis in every language. Could you do that? We also didn't translate it beforehand.

**Comment by ruddygasol94** [comment]
It's ok, don't worry. I already replicate it to the language files and make an initial translation.
