### ISSUE TITLE
Update Book_of_HOPR

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#205]
# Page
https://hoprnet.org/de/assets/documents/Book_of_HOPR_v1.pdf

# Current behavior
Dated pdf

# Expected behavior
Please replace the file with the following: 
https://drive.google.com/file/d/1QKbBRKHE26Ju9QnRq3jAF8aix3jth8jX/view

**Comment by ruddygasol94** [comment]
Can we have access to the file, please.

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 Sorry, now enabled
