### ISSUE TITLE
"TESTNET" link in header linkes to Saentis.*

### ISSUE THREAD

**Issue by kitschbent** [hoprnet/hoprnet-org#208]
# Page

Home (/), the link for TESTNET in the banner

# Current behavior

This hyperlinks to saentis.*, which redirects to https://network.hoprnet.org/ (which is for Basodino testnet)

# Expected behavior

This should link to our current network, Jungfrau, and those install docs. 

The test should also be updated from TESTNET to 'RUN A NODE', 'RUN NODE', etc...

**Comment by ruddygasol94** [comment]
Quick question, so the link must redirect to install docs?

**Comment by ReinhardSchmidt** [comment]
@kitschbent FYI, above

**Comment by kitschbent** [comment]
I would suggest renaming the link to "RUN A NODE" and making it link
directly to the install page in the docs, here:
https://docs.hoprnet.org/en/latest/src/install-hoprd/index.html

Matthew Edwards
Head of Web3 Marketing
+1.828.358.3088

**Comment by kitschbent** [comment]
this still redirects here: https://network.hoprnet.org/

Matthew Edwards
Head of Web3 Marketing
+1.828.358.3088
