### ISSUE TITLE
/technology white space-issue

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#210]
# Page
/technology

# Current behavior
white space:
![Bildschirmfoto 2021-03-30 um 12 13 23](https://user-images.githubusercontent.com/78225531/112973215-5e92f580-9151-11eb-8ce4-bfb360bb58ce.png)

# Expected behavior
only as much white space as possible, if it becomes apparent that this is an global issue, please fix it analogue to here

**Comment by ruddygasol94** [comment]
![Captura de Pantalla 2021-03-30 a la(s) 19 15 19](https://user-images.githubusercontent.com/11565775/113076454-5015ff80-918c-11eb-8a13-6704b57547c3.png)

I see it already without white space, maybe waiting for the pull to verify.

**Comment by jjperezaguinaga** [comment]
Confirm that this is no longer an issue, closing.
