### ISSUE TITLE
[ website bug ] "Run node" does not help people run a node

### ISSUE THREAD

**Issue by jlherren** [hoprnet/hoprnet-org#213]
This has been bothering me for a while. The "Run node" link in the main menu leads to [network.hoprnet.org](https://network.hoprnet.org/), with the leaderboard of the past Basòdino v2 testnet. If a visitor then clicks on the "Help" button, they get instructions on how to install the deprecated HOPR Chat and that they must send Matic to the node... this is all massively confusing for any newcomer that wants to set up a node.

# Page
"Run node" in main menu on every page: https://hoprnet.org/

# Current behavior
Links to https://network.hoprnet.org/

# Expected behavior
Somewhere actually useful to run a node, for example https://docs.hoprnet.org/en/latest/src/install-hoprd/index.html

**Comment by jjperezaguinaga** [comment]
@jlherren That's actually not a bad point, I was just _now_ discussing w/ @ReinhardSchmidt about pointing our users to the Docs. What do you think @kitschbent ?

**Comment by ReinhardSchmidt** [comment]
But then let´s also rename the button to "Documentation"

**Comment by kitschbent** [comment]
I personally think we could do with two then. one called DOCS pointing to
the docs landing page, and the other for running a node. as, after all, we
need #s of node runners and having that clear and up top should perhaps be
there. not sure if that makes too much noise on the top then though,
without adding drop downs...

**Comment by kitschbent** [comment]
talked with Reinhard...

DOCS -- link to https://docs.hoprnet.org/

RUN NODE -- link to the github readme, as the software is hosted here. in future when network dashboard is set up, if there is a brief install guide (or link), we can send them there rather than the github, but for now this is best

**Comment by ReinhardSchmidt** [comment]
@ruddy see the two requests above. Many thanks!

**Comment by ReinhardSchmidt** [comment]
Correct. 
@ruddygasol94 Last step, can you change the order of the points in the menue to the following:
"RUN NODE", "DOCS", "BLOG"

**Comment by ruddygasol94** [comment]
@ReinhardSchmidt  Sure! Let me do it.
