### ISSUE TITLE
Is there a way to link directly to the JOBS-section on /About-us ?

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#223]
# Page
The jobs-section on /about-us

# Current behavior
not accessible directly through an external adress

# Expected behavior
We want to link directly to all our jobs in one central place in the future, the current about-us is contentwise too diverse.

What would therefore make more sense, be applicable:
- is it possible to create some URL-"subroutine" in order to access the Prescreen-Jobspanel directly ON About-us?
![Bildschirmfoto 2021-04-12 um 16 53 46](https://user-images.githubusercontent.com/78225531/114415120-af720780-9baf-11eb-825f-78817bf14769.png)
- If not: move the panel into an newly formed "Jobs"-section, featured inside the footer

**Comment by ruddygasol94** [comment]
It would be like this: "/about-us#jobs"

**Comment by ReinhardSchmidt** [comment]
Sounds great! What we needed.
