### ISSUE TITLE
/technology remove white space

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#228]
# Page
/technology

# Current behavior
way too big white space at end of section 1
![Bildschirmfoto 2021-04-13 um 14 26 11](https://user-images.githubusercontent.com/78225531/114553468-f28eb200-9c65-11eb-9b77-d08bf48f1825.png)

# Expected behavior
white space

**Comment by ruddygasol94** [comment]
In the link https://hoprnet-org-v2-git-development-hoprnet.vercel.app/technology, I see it without the white space, maybe soon with the update, it would be fixed.

**Comment by ReinhardSchmidt** [comment]
Thanks

**Comment by jjperezaguinaga** [comment]
Closed as this was already solved time ago.
