### ISSUE TITLE
/about us: team-icons look cropped

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#274]
# Page
/about us

# Current behavior
the circles started to look cropped for some reason (lefts outside of Amiras' icon for example):
![Bildschirmfoto 2021-05-31 um 10 41 05](https://user-images.githubusercontent.com/78225531/120166308-bce55e80-c1fc-11eb-8542-388910864dd4.png)

# Expected behavior
show the native file without crops. Or ist this a failure that went unnoticed on my side?

**Comment by ruddygasol94** [comment]
Hello @ReinhardSchmidt, what resolution or device are you using? I already try it on mobile, iPad, and desktop and I don't see the circle cropped.

Thanks,
