### ISSUE TITLE
Add yellow paper to the website

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hoprnet-org#291]
https://github.com/hoprnet/hoprnet/blob/yellowpaper/docs/yellowpaper/yellowpaper.pdf

**Comment by mathcrypto** [comment]
You can replace that link by the one in the master branch https://github.com/hoprnet/hoprnet/blob/master/docs/yellowpaper/yellowpaper.pdf

**Comment by ReinhardSchmidt** [comment]
@mathcrypto this is not the final version as @tolbrino and @thewanderingeditor @SCBuergel  still need to add their edits.

**Comment by tolbrino** [comment]
That is correct. Also do not link to the master branch, since that will always be WIP. Link to the specific Git hash we will agree upon.
