### ISSUE TITLE
/token please remove the underlining for "How to stake HOPR" in the button text

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#295]
# Page
/token

# Current behavior
"How to stake HOPR" is underlined
![Bildschirmfoto 2021-08-20 um 16 32 28](https://user-images.githubusercontent.com/78225531/130252105-eb179144-9cae-4239-92d7-170a1d033fdd.png)

# Expected behavior
remove the underlining

**Comment by QuinsZouls** [comment]
Fixed in fcbc9936b5c977ae9fbedac7512850414e772d0a
