### ISSUE TITLE
/partner link is dead

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hoprnet-org#297]
# Page
http://hoprnet.org/partner is linked in explainer videos like https://www.youtube.com/watch?v=emgl4FC8Rko&list=PLWWV8SUQ3oGYT464IXqEZb_Sr5HGyY9YG&index=2 but that link is dead

# Current behavior
404

# Expected behavior
link to same page as /partners (With an s in the end)

**Comment by ReinhardSchmidt** [comment]
@ruddygasol94 could you please add this forwarding?

**Comment by jjperezaguinaga** [comment]
Closed in #301
