### ISSUE TITLE
INTERNAL: please URL-fwd from hoprnet.io, hopr.tech, hopr.link to hopr.swiss

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#330]
# Current behavior
not enabled

# Expected behavior
please URL-fwd from hoprnet.io, hopr.tech, hopr.link to hopr.swiss
@tolbrino

**Comment by ReinhardSchmidt** [comment]
this is sth for @tolbrino

**Comment by tolbrino** [comment]
So hoprnet.io is being phased out?

**Comment by ReinhardSchmidt** [comment]
Please forward from hoprnet.io to hopr.swiss in order that hoprnet.org is THE ONLY iteration of the AG-website.

**Comment by tolbrino** [comment]
- hoprnet.link **done**

We don't have hopr.link, so I consider this task done.
