### ISSUE TITLE
INTERNAL: please reg. clients@hopr.swiss and have it fwd to tech@hoprnet.org

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#331]
# Current behavior
unregistered

# Expected behavior
Please reg. clients@hopr.swiss and have it fwd to tech@hoprnet.org

**Comment by ReinhardSchmidt** [comment]
@tolbrino

**Comment by tolbrino** [comment]
What type of messages are expected on that new address? Why should it go to tech?

**Comment by ReinhardSchmidt** [comment]
It will concern emails of interested clients that got the mail address from hopr.swiss.
 
It should go to the tech@ in order to ensure that it gets read. Otherwise Sebastian would need to set-up an separate clients@ and keep continue checking it.

**Comment by tolbrino** [comment]
Done.

**Comment by ReinhardSchmidt** [comment]
Just tried it and got a 550. Can you please re-check?

**Comment by tolbrino** [comment]
Done now.
