### ISSUE TITLE
/token: remove Month in the token distribution-chart

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#338]
# Introduction

# Task description
Please remove the "Month"-count in the x-Axis AND the overlay of EVERY language, as we‘re going to update the field to state "Feb 2021" or similar, as in the "data-supply.json" of branch "…patch-3-1" already realised:
<img width="1082" alt="Bildschirmfoto 2021-11-17 um 13 52 40" src="https://user-images.githubusercontent.com/78225531/142206072-e33eb417-4f1c-44d2-8a88-5b704ddfce05.png">

# Definition of complete

**Comment by CristianGomezO** [comment]
design #340 - remove Month in all languages
