### ISSUE TITLE
/token occurence of clipping/cut chart

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#342]
# Page

# Current behavior
The depictions on the x-Axis are not shown in it‘s entirety

![Bildschirmfoto 2021-11-19 um 10 13 15](https://user-images.githubusercontent.com/78225531/142597253-9ca3ddc0-3296-461b-a252-eb7473dfdaca.png)
![Bildschirmfoto 2021-11-19 um 10 13 02](https://user-images.githubusercontent.com/78225531/142597260-45493f9d-ac1c-4677-b2b5-abe04625182e.png)
![Bildschirmfoto 2021-11-19 um 10 12 52](https://user-images.githubusercontent.com/78225531/142597262-ca5c8c53-9eb8-49ac-a67f-5957e674ad1a.png)

# Expected behavior
Display completely

**Comment by betinho89** [comment]
Hi @ReinhardSchmidt , can you please provider more information about this issue, because we can't reproduce.

**Comment by ReinhardSchmidt** [comment]
Right, also can‘t reproduce the issue anymore.
