### ISSUE TITLE
/token: Skewed icon

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#344]
# Page
/token, in the Features-section 

# Current behavior
The Voting-icon is being displayed skewed although it‘s correct in native form
![Bildschirmfoto 2021-11-26 um 17 48 50](https://user-images.githubusercontent.com/78225531/143613798-c440bf1d-8c48-43ba-964c-4ae2adca0bd1.png)

# Expected behavior

**Comment by CristianGomezO** [comment]
#347 - icon style corrected
