### ISSUE TITLE
/token on Safari 14.1.2 and iOS 14: broken icons

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#368]
<img width="1440" alt="Bildschirmfoto 2022-01-10 um 10 26 04" src="https://user-images.githubusercontent.com/78225531/148743476-94caa7c5-ef14-449b-b577-3188e71a099b.png">

**Comment by CristianGomezO** [comment]
In this safari version the icons are not broken, and an older version cannot be downloaded.
![Screenshot_1](https://user-images.githubusercontent.com/41966303/149031926-84d2a91f-2272-4e0f-8c9a-666550f657db.png)

**Comment by jjperezaguinaga** [comment]
@ReinhardSchmidt can you share your OS, Safari version and workstation details?

**Comment by CristianGomezO** [comment]
Hello!, could you check in Safari 14.1.2 and iOS 14 if the icons were fixed?
