### ISSUE TITLE
/hop-on-board: move the blue "Location"-mark in the schedule

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#375]
# Page

# Current behavior
All lines of Week 1 are marked in blue
<img width="920" alt="Bildschirmfoto 2022-01-17 um 09 27 59" src="https://user-images.githubusercontent.com/78225531/149776422-bfeea913-5967-460f-9b14-c4570704282f.png">

# Expected behavior
- Mark all lines of week 3 in blue
- please post here the "locales-path" in order that I can do these changes on my own

**Comment by CristianGomezO** [comment]
Relative path: service\components\organisms\section-road-map-hop.js
