### ISSUE TITLE
https://hoprnet.org/blog - unavailable/empty

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#381]
# Page
blog

# Current behavior
<img width="1440" alt="Bildschirmfoto 2022-01-20 um 21 12 09" src="https://user-images.githubusercontent.com/78225531/150414673-1cbd8a64-68f4-4df2-91bc-09f4794ecbba.png">

# Expected behavior
make it appear again :)

**Comment by CristianGomezO** [comment]
It is down
![error](https://user-images.githubusercontent.com/41966303/150587092-2e3b2b55-b682-46b2-8a4b-8071e6772590.png)

**Comment by ReinhardSchmidt** [comment]
Is the API permanently down?

On the actual platform it‘s still working: https://medium.com/hoprnet

**Comment by ReinhardSchmidt** [comment]
Was there a reason of not using the direct Medium API:
https://github.com/Medium/medium-api-docs 
 instead of the Pixelpoint?

**Comment by CristianGomezO** [comment]
Can you please generate the access token from the medium panel to be able to make the requests
![Screenshot_1](https://user-images.githubusercontent.com/41966303/150875796-ad0b8844-3096-4073-a54c-f9973fb2278d.png)
?

**Comment by ReinhardSchmidt** [comment]
Great!! We created the following token:
2f3f9b66d0adaaae21bb5254c700bb5fe42d223ffa7a50bac413b11701bf9dfb7

**Comment by ReinhardSchmidt** [comment]
userId: @hoprteam

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO Could you find some time to look into it? :)

**Comment by CristianGomezO** [comment]
Still not working 
![image](https://user-images.githubusercontent.com/41966303/151595338-5c5e4cde-3ae5-4033-abc4-f39cfbab299f.png)
![image](https://user-images.githubusercontent.com/41966303/151595375-730d4a2d-6cfc-4b96-b60a-ca94e120fb21.png)

**Comment by Jaguaras** [comment]
@CristianGomezO Hey! Would it be possible to give a link to this tool? so we could test it locally and check which access token will work out?

**Comment by CristianGomezO** [comment]
https://api.medium.com/v1/users/{userId}/publications

**Comment by Jaguaras** [comment]
> https://api.medium.com/v1/users/{userId}/publications

thanks, how you append access token to the given url? Because it requires.

**Comment by CristianGomezO** [comment]
in Postman in the authorization tab just choose the Bearer Token type and put the token.
![image](https://user-images.githubusercontent.com/41966303/152038415-26b6311a-64d4-4a09-b9f3-f3695e09895e.png)
