### ISSUE TITLE
/Home: change Use-case module 

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#383]
# Introduction
We would like to update our use-case module.

# Task description
- please delete on /home the third segment (the one after the three taboid/media-quotes):
<img width="667" alt="Bildschirmfoto 2022-01-23 um 22 15 06" src="https://user-images.githubusercontent.com/78225531/150698222-784c30be-5b90-4ef2-a3d4-ad303b286297.png">

# Definition of complete
<img width="585" alt="Bildschirmfoto 2022-01-24 um 00 08 36" src="https://user-images.githubusercontent.com/78225531/150701822-45434f2f-ca4b-40bd-8f27-3bae72c42b8e.png">

UI is implemented: https://www.figma.com/file/x7UYVr4FbehVWEoef5BwbB/HOPR_Use-case-Module-copy?node-id=0%3A1
Copy is pasted: https://docs.google.com/document/d/1OOu8IyxD5swlO0XmvsriSMJOBokgTiq0ao3lu5T4wjY/edit
hopr-medtech-use-case.gif:
https://drive.google.com/open?id=1JEZ_6DNFD98W0Gr2GoiN9uNVqWHndndL&authuser=zrh%40hoprnet.org&usp=drive_fs

hopr-defi-use-case.gif: https://drive.google.com/file/d/1JI6FpYJaOZsJgq-5RaRwDr7qH3Aq1ooX/view?usp=sharing

**Comment by CristianGomezO** [comment]
Could you give me access to the document please?, thank you very much
![image](https://user-images.githubusercontent.com/41966303/150880743-74fee997-821c-4386-b91f-2dcce9ce9bc6.png)

**Comment by ReinhardSchmidt** [comment]
Sorry, now enabled. We will from now ensure that this doesn't happen again.
