### ISSUE TITLE
/hop-on-board Update roadmap titles

### ISSUE THREAD

**Issue by sirjaycrypto** [hoprnet/hoprnet-org#406]
# Introduction

The roadmap on the /hop-on-board site needs to be updated to more accurately fit our current status of developement. 

# Task description

Change the List on /hop-on-board to the following (italic for changes):

> Week 1:
> Plan the route…
> Launch Announcement
> 
> Week 2:
> Get Your Tickets...
> Staking Transfer and DAO Fulfillment Update
> 
> Week 3:
> Hop on board…
> Staking 2.0 and IP Privacy Week
> WE’RE OFF!
> 
> Week 4:
> ZURICH
> **_D.E.R.P. showcases_**
> 
> Week 5:
> ZUG
> **_Privacy Interviews & Meetups_**
> 
> Week 6:
> ROTKREUZ
> **_Matterhorn Public Testnet_**
> 
> Week 7:
> LUZERN
> BUIDL Week @ETHDenver
> 
> Week 8:
> ALTDORF
> **_First HOPR dApp_**
> 
> Week 9:
> CHUR
> Hidden - Blue Rectangle
> 
> Week 10:
> DISENTIS/MUSTER
> Hidden - Blue Rectangle
> 
> Week 11:
> ANDERMATT (arr)
> **_IP Privacy Week #2_**
> 
> Week 12:
> ANDERMATT (dep)
> **_Hidden - Blue Rectangle_**
> 
> Week 13:
> GOMS
> Hidden - Blue Rectangle
> 
> Week 14:
> FIESCH
> Hidden - Blue Rectangle
> 
> Week 15:
> BRIG
> Hidden - Blue Rectangle
> 
> Week 16:
> RANDA
> Mega BUIDL Week @ETHAmsterdam

# Definition of complete

The task is completed when the "Schedule"-section from https://hoprnet.org/de/hop-on-board shows the above list with the respective hidden boxes.

# Testing criteria

(Write your answer here.)

# Additional notes

A first PR was made, but we realized, we're not able to change the blue boxes ourselves: https://github.com/hoprnet/hoprnet-org/pull/405

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO could you please look into this within todays‘ shift?
