### ISSUE TITLE
/hop-on-board: replace HERO with image during ETH Denver due to bandwidth issues

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#409]
# 
Page
/hop-on-board

# Expected behavior
- please host instead of the video, for the moment an image with the same resolution: 
https://drive.google.com/file/d/1MvlvqUN3u8fpn8SLUXXyCGp9hBhrmGos/view?usp=sharing
- please comment the vimeo-hero-function out, want to reactivate it in a week

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO could you please revert it back to the one with video-state?

**Comment by CristianGomezO** [comment]
#418 Hello, in this pr it is solved
