### ISSUE TITLE
Irritating loading-behaviour (jump to top) when using the Jobs-module in /about-us and /hop-on-board

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#411]
# Page
/about-us
/hop-on-board

# Current behavior
<img width="1440" alt="Bildschirmfoto 2022-02-21 um 11 58 53" src="https://user-images.githubusercontent.com/78225531/154942820-755a664f-c895-4807-bd9d-db649dc1ac12.png">

When clicking on a listed job position (see screenshot) the current page is being reloaded entirely, and more importantly: a jump to the top of the page is executed. The user then needs to scroll down again in order to see the detail information of a position.

QUESTION: Can the content of the jobs module be loaded in another way? One that avoids a jump to the top?

**Comment by CristianGomezO** [comment]
We are going to need access to the jobs script to edit and fix it.

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO gave Beto yesterday via our messenger-group the login details of prescreen. He can provide them to you.

**Comment by Jaguaras** [comment]
Thanks, solved!
