### ISSUE TITLE
Add Icon for Team-Member Melissa Günthardt

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#412]
# Page
please add Melissa Günthardt.

# Expected behavior
"Melissa Günthardt
Marketing Specialist"
https://drive.google.com/open?id=1NlnO2EFa3ujP4ar_2x6ElR8yTcZYdaAH&authuser=zrh%40hoprnet.org&usp=drive_fs

**Comment by CristianGomezO** [comment]
She already exists
![image](https://user-images.githubusercontent.com/41966303/155209931-f24678ae-ab56-4387-adaa-c2665a02ba83.png)
