### ISSUE TITLE
Add Use 3 to /home

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#421]
# Page
https://hoprnet.org/

# Expected behavior
add a third use-case to the module:
![Bildschirmfoto 2022-03-08 um 12 35 09](https://user-images.githubusercontent.com/78225531/157234330-80db4b20-9dea-4f52-be5c-4357888356d6.png)

Add Copy:
Headline "Use Case 3: Decentralized Energy"

Running text 
"In decentralized energy markets, energy suppliers are matched directly with buyers. To avoid price manipulation, buyers and sellers must not know the full details of who they are matched with, but still need confidence they're buying / selling the correct amount of energy for the right price.

In addition, third-party observers must not be able to derive the topology of the network by observing transactions.

This complex challenge can only be resolved using a metadata-private network like HOPR."

gif: https://drive.google.com/file/d/1bNGJOlu_FvbF9Orrg_5NfU8UC76oB5uF/view?usp=sharing

**Comment by CristianGomezO** [comment]
Could you give me access to the drive please
![image](https://user-images.githubusercontent.com/41966303/157494904-fcc76024-9fa3-4ae1-a0e9-44bc031f19cf.png)
