### ISSUE TITLE
Insert four more logos into "Investors"-section

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#426]
# Page
/about-us
/token - there into the "BACKED BY"-section

# Current behavior

# Expected behavior
please add these four images AT THE END OF THE BLOCK
![Bildschirmfoto 2022-03-16 um 09 59 17](https://user-images.githubusercontent.com/78225531/158554710-dbb28082-e81d-4c0e-9cdb-796e53d680a0.png)

ANKR: https://www.ankr.com/
HARMONY: https://www.harmony.one/
DUSK: https://dusk.network/
THE GRAPH: https://thegraph.com

Files, access enabled: 
https://drive.google.com/drive/folders/1-RsGnfJ-miBLtJsxj9eyEvwOlavlOvUx?usp=sharing

**Comment by Jaguaras** [comment]
Thanks! Solved
