### ISSUE TITLE
State of the page "2 of 3" online during 21st to 24th Feb: update Price, set Button link to "XXXX" - to be announced soon

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#56]
Manual price-insert for Pre-Sale-State, current value is not ours (Sebastian/Rik need to assign it). Keep you posted. But this is part of the milestone "Public state of the page 1 of 3".

![Bildschirmfoto 2021-02-09 um 13 22 27](https://user-images.githubusercontent.com/78225531/107363042-e0638c80-6ad9-11eb-861f-20a9951f718c.png)

**Comment by jjperezaguinaga** [comment]
@ReinhardSchmidt agreed with @SCBuergel to leave it like this for now.
