### ISSUE TITLE
Information on our side missing: Public state of the page "2 of 3", inside Disclaimer: set correct new tab-Link to the Community-launch sales page

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hoprnet-org#57]
This should apply for:
- every "I agree button" in any disclaimer on the site to "XXX" yet to be assigned:
![Bildschirmfoto 2021-02-09 um 13 24 21](https://user-images.githubusercontent.com/78225531/107363238-27ea1880-6ada-11eb-8740-370be0419690.png)

- When clicking on "Get HOPR Token" – please forward to "XXX" yet to be assigned:
![Bildschirmfoto 2021-02-09 um 13 25 24](https://user-images.githubusercontent.com/78225531/107364134-561c2800-6adb-11eb-8222-4843a7d270b5.png)

**Comment by jjperezaguinaga** [comment]
Solved in #77
