### ISSUE TITLE
Scaling / Cropping for Token Distribution Graph is Wrong

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hoprnet-org#89]
# Page
On the token page, in the Token Release section

# Current behavior
The Token Release graph is cropping the labels out of the x-axis. The scaling is also wrong on many browsers.

# Expected behavior
Graph should be sensibly scaled and all labels visible.

# Possible solution
For the labelling, it might be possible to add a general label "Months after launch" and then replace the individual labels with just numbers (e.g., 0, 6, 12, etc.). That would then require less vertical space.
![Graph Cropping](https://user-images.githubusercontent.com/29358947/107851200-12d5f800-6e00-11eb-84dc-4af22bfe7758.png)
![Graph Cropping 2](https://user-images.githubusercontent.com/29358947/107851211-3ac55b80-6e00-11eb-814f-2f2c3fe2bd57.png)

**Comment by jjperezaguinaga** [comment]
Solved in #98
