### ISSUE TITLE
Token Supply Distribution graph not rendering months correctly

### ISSUE THREAD

**Issue by WRRichter** [hoprnet/hoprnet-org#90]
# Page

/token
(Write your answer here.)

# Current behavior

(Write your answer here.)
Token Supply Distribution graph not rendering months correctly
# Expected behavior

Months show completely
(Write your answer here.)

# Possible solution

(Write your answer here.)

# Usepastel link

(Write your answer here.)

# Screenshots

![image](https://user-images.githubusercontent.com/77666766/107851228-ba572880-6e08-11eb-8f80-6bd0caf1f0f1.png)

## Detailed Description

(Write your answer here.)

## Context (Environment)

- Device: 
- OS: 
- Browser:
- Version:

**Comment by jjperezaguinaga** [comment]
Has been solved already in #98
