### ISSUE TITLE
Some pages have problems!

### ISSUE THREAD

**Issue by serkan-kaya** [hoprnet/hoprnet-org#95]
Some menu pages have problems. Variables come instead of titles.

Sample 1- Blog Page

![image](https://user-images.githubusercontent.com/75005293/107857601-46387700-6e40-11eb-9bd2-09a274a01feb.png)

Sample 2 - Technology Page
![image](https://user-images.githubusercontent.com/75005293/107857611-67996300-6e40-11eb-9c3e-0c2f6f8dcd06.png)

**Comment by jjperezaguinaga** [comment]
Solved in #98
