### ISSUE TITLE
font size Chinese token page 'backed by from partners'

### ISSUE THREAD

**Issue by mengluw** [hoprnet/hoprnet-org#97]
<img width="1263" alt="Screenshot 2021-02-13 at 20 05 12" src="https://user-images.githubusercontent.com/79019677/107858975-15a00f80-6e37-11eb-8235-cb3596dea748.png">
# Page

roll down where the three comments from three partners 

<img width="1263" alt="Screenshot 2021-02-13 at 20 05 12" src="https://user-images.githubusercontent.com/79019677/107858987-2486c200-6e37-11eb-87e6-75bb17d9de4d.png">

# Current behavior

(Write your answer here.)

# Expected behavior

it would look visually better if the font size is slightly smaller 

# Possible solution

(Write your answer here.)

# Usepastel link

(Write your answer here.)

# Screenshots

## Detailed Description

(Write your answer here.)

## Context (Environment)

- Device: 
- OS: 
- Browser:
- Version:

**Comment by jjperezaguinaga** [comment]
Discussed with @mengluw about this one, and decided to close for the time being.
